version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: "SEOnaut-db"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=seonaut
      - MYSQL_USER=seonaut
      - MYSQL_PASSWORD=seonaut
    networks:
    - seonaut_network

  app:
    build: .
    container_name: "SEOnaut-app"
    ports:
      - "${SEONAUT_PORT:-9000}:9000"
    depends_on:
      - db
    command: sh -c "/bin/wait && /app/seonaut"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
    - seonaut_network

networks:
  seonaut_network:
    driver: bridge
